### ISSUE TITLE
NLA - New Operatore "Bake Actions" needs to be added

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#265] opened 2022-05-02 16:58 UTC
New operator, new documentation needed
![image](https://user-images.githubusercontent.com/35357409/166980233-271ede57-617e-408b-bf0f-2d7f949914e5.png)

Linked Task:
[https://github.com/Bforartists/Bforartists/issues/2985](https://github.com/Bforartists/Bforartists/issues/2985)

**Comment by ReinerBforartists** [comment] 2022-05-02 17:13
I would always add a picture of it. Menu location for example. Makes life easier.

**Comment by Draise14** [comment] 2022-05-05 17:33
Image added

**Comment by Draise14** [comment] 2022-05-05 17:59
Added operator and images
![image](https://user-images.githubusercontent.com/35357409/166984428-f9c30c35-8650-4922-a94c-1c9dbc8e360e.png)

Added text from here:
https://docs.blender.org/manual/en/latest/animation/actions.html?highlight=nla%20bake%20action#bake-action

Pending commit.

**Comment by ReinerBforartists** [comment] 2022-05-05 18:35
Be careful with copy n paste and licensing issues!

**Comment by Draise14** [comment] 2022-05-05 19:40
Ah ok.. I see. I have updated it to be unique. 
![image](https://user-images.githubusercontent.com/35357409/167012765-a848f907-8a96-49f7-8d34-bb7a515fc892.png)

The blender documentation is NOT GNU or CC0. I had no idea, just assumed - will be more careful next time. 
`© [Copyright](https://docs.blender.org/manual/en/latest/copyright.html) : This page is licensed under a CC-BY-SA 4.0 Int. License. Last updated on 05/02/2022.`

**Comment by ReinerBforartists** [comment] 2022-05-06 06:20
Many thanks :)

Ah, ccby. I always mix it ... 

Well. Technically the Blender manual is still under OCL License since the Blender developers did not ask everybody involved when they changed the licensing for the manual. And this twice. They changed it from OCL to CC0, and then to CCBY without asking anybody. So the current licensing is simply illegal. But i am not really keen to fight this with a lawsuit. And with CCBY you need to name your sources and give credit (CC0 is the one where you don't have to give credit afaik). Also mission impossible since the Blender developers also fails at this point.

**Comment by ReinerBforartists** [comment] 2022-05-07 07:15
When the commit is pending then the issue is not fixed yet. Please don't add a fixed label then. 

An issue is fixed when the code or the file is committed.

**Comment by ReinerBforartists** [comment] 2022-05-07 08:43
How far are you with this?

**Comment by Draise14** [comment] 2022-05-07 14:22
I put the fixed tag to say this task is done. Now just pending the commit. But I want to do the other ones first to do multiple take in one commit as suggested for bandwidth. 

I suggest for this workflow to be organized:
1. Fixed means done. No more work needed. Can remain open till committed. 
2. Closed means it's committed

This means I can track what I've done in the tracker without multiple commits and closed tasks and also track what hasn't been committed yet to be organized.

**Comment by ReinerBforartists** [comment] 2022-05-07 15:41
No. Fixed means it is in the master. It is not fixed as long as it is not in the master. Everything else just leads to complete confusion since i cannot know what part you have fixed.

**Comment by Draise14** [comment] 2022-05-07 15:43
Ah ok. Means I have to commit to close.

**Comment by ReinerBforartists** [comment] 2022-05-07 15:43
Yes, please :)

**Comment by ReinerBforartists** [comment] 2022-05-07 15:44
Please make a git fetch and git pull. I have commited today.

**Comment by ReinerBforartists** [comment] 2022-05-07 16:18
> Ah ok. Means I have to commit to close.

Just that we don't misunderstand each other. This also means,  the fixed label comes afterwards. There can go so much wrong between "i have fixed it locally" and "it's finally in the master". So first commit, then close, then add the fixed label. The task is not fixed as long as the code (or the file) is not in the github repository.

**Closed** 2022-05-07 16:42 UTC
Labels: 1 - Task
