### ISSUE TITLE
Dope Sheet - Action Editor mode - New panel "Custom Properties" 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#303] opened 2022-06-28 17:05 UTC
![image](https://user-images.githubusercontent.com/35357409/176241537-d7e49031-8086-4e21-9657-c5f2a3f3fb28.png)

New panel needs documentation

**Comment by ReinerBforartists** [comment] 2022-07-06 07:05
Duplicate of https://github.com/Bforartists/Manual/issues/304

**Closed by ReinerBforartists** 2022-07-06 07:05 UTC
Labels: 1 - Task
