### ISSUE TITLE
UV Editor - New "Select Similar" operator needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#299] opened 2022-06-28 16:34 UTC
![image](https://user-images.githubusercontent.com/35357409/176233248-fbddb2d3-c300-4a15-a731-4ea875d4da31.png)

New operator, new documentation needed

Relevant Task:
https://github.com/Bforartists/Bforartists/issues/3088

**Comment by ReinerBforartists** [comment] 2022-07-06 07:06
Duplicate of Document new select similar pinned operator. #308

**Closed by ReinerBforartists** 2022-07-06 07:06 UTC
Labels: 1 - Task
